#!/bin/bash

# here we need to fix all the lua/after file to comment out everything that isn't installed yet
# i.e. --[[ should become ---[[

# setup packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
